default_install_hook_types:
-   pre-commit
-   pre-push

default_stages: [pre-commit]


repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-json
        types: [json]
    -   id: check-merge-conflict
    -   id: check-case-conflict
    -   id: mixed-line-ending
        args: ['--fix=lf']
    -   id: double-quote-string-fixer
        types: [python]
    -   id: end-of-file-fixer
        stages: [pre-commit]
    -   id: pretty-format-json
        args: ['--autofix']
        types: [json]
    -   id: trailing-whitespace
        exclude: '\.md$'

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.6
    hooks:
    -   id: ruff-check
    -   id: ruff-format

-   repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.13
    hooks:
    -   id: uv-lock
