[project]
name = "alfred"
version = "0.1.0"
description = "alfred"
readme = "README.md"
requires-python = ">=3.11,<3.14"
dependencies = [
    "awesome-streamlit>=20200728.1",
    "bokeh>=3.8.1",
    "curl-cffi==0.7.4",
    "lxml>=6.0.2",
    "matplotlib>=3.10.7",
    "numpy>=2.3.5",
    "pandas>=2.3.3",
    "requests>=2.32.5",
    "scikit-learn>=1.7.2",
    "streamlit>=1.51.0",
    "tensorflow>=2.20.0",
    "yfinance==0.2.58",
]

[dependency-groups]
dev = [
    "coverage>=7.6.12",
    "pre-commit>=4.0.1",
    "pytest>=8.3.4",
]

[tool.ruff]
fix = true
line-length = 120
lint.ignore = ["COM812", "D100", "D101", "D102", "D103", "D107", "D400", "D415", "NPY002", "T201"]
lint.select = ["ALL"]

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"
